version: "3"
services:
  redis:
    image: redis:6.2.3
    container_name: adachi-redis
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./database:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
  bot:
    build: .
    container_name: adachi-bot
    environment:
      docker: "yes"
    depends_on:
      - redis
    volumes:
      - ./config:/bot/config
      - ./src/plugins:/bot/src/plugins
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"